// <auto-generated />
using System;
using KarapinhaAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KarapinhaAPI.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240614150930_first-migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KarapinhaAPI.Models.Categoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCategoria"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Marcacao", b =>
                {
                    b.Property<int>("IDMarcacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMarcacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IDUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDMarcacao");

                    b.HasIndex("IDUtilizador");

                    b.ToTable("Marcacoes");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Profissional", b =>
                {
                    b.Property<int>("IDProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProfissional"));

                    b.Property<string>("BilheteIdentidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IDProfissional");

                    b.HasIndex("IDCategoria");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Servico", b =>
                {
                    b.Property<int>("IDServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDServico"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IDServico");

                    b.HasIndex("IDCategoria");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.ServicoMarcacao", b =>
                {
                    b.Property<int>("IDMarcacao")
                        .HasColumnType("int");

                    b.Property<int>("IDServico")
                        .HasColumnType("int");

                    b.Property<int>("IDProfissional")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.HasKey("IDMarcacao", "IDServico", "IDProfissional");

                    b.HasIndex("IDProfissional");

                    b.HasIndex("IDServico");

                    b.ToTable("ServicoMarcacoes");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.ServicoProfissional", b =>
                {
                    b.Property<int>("IDProfissional")
                        .HasColumnType("int");

                    b.Property<int>("IDServico")
                        .HasColumnType("int");

                    b.HasKey("IDProfissional", "IDServico");

                    b.HasIndex("IDServico");

                    b.ToTable("ServicoProfissionais");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Utilizador", b =>
                {
                    b.Property<int>("IDUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUtilizador"));

                    b.Property<string>("BilheteIdentidade")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeUtilizador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUtilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Marcacao", b =>
                {
                    b.HasOne("KarapinhaAPI.Models.Utilizador", "Utilizador")
                        .WithMany("Marcacoes")
                        .HasForeignKey("IDUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Profissional", b =>
                {
                    b.HasOne("KarapinhaAPI.Models.Categoria", "Categoria")
                        .WithMany("Profissionais")
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Servico", b =>
                {
                    b.HasOne("KarapinhaAPI.Models.Categoria", "Categoria")
                        .WithMany("Servicos")
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.ServicoMarcacao", b =>
                {
                    b.HasOne("KarapinhaAPI.Models.Marcacao", "Marcacao")
                        .WithMany("ServicoMarcacoes")
                        .HasForeignKey("IDMarcacao")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KarapinhaAPI.Models.Profissional", "Profissional")
                        .WithMany("ServicoMarcacoes")
                        .HasForeignKey("IDProfissional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarapinhaAPI.Models.Servico", "Servico")
                        .WithMany("ServicoMarcacoes")
                        .HasForeignKey("IDServico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Marcacao");

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.ServicoProfissional", b =>
                {
                    b.HasOne("KarapinhaAPI.Models.Profissional", "Profissional")
                        .WithMany("ServicoProfissionais")
                        .HasForeignKey("IDProfissional")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KarapinhaAPI.Models.Servico", "Servico")
                        .WithMany("ServicoProfissionais")
                        .HasForeignKey("IDServico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Categoria", b =>
                {
                    b.Navigation("Profissionais");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Marcacao", b =>
                {
                    b.Navigation("ServicoMarcacoes");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Profissional", b =>
                {
                    b.Navigation("ServicoMarcacoes");

                    b.Navigation("ServicoProfissionais");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Servico", b =>
                {
                    b.Navigation("ServicoMarcacoes");

                    b.Navigation("ServicoProfissionais");
                });

            modelBuilder.Entity("KarapinhaAPI.Models.Utilizador", b =>
                {
                    b.Navigation("Marcacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
